import type { Listing, Application } from "./api";

export const mockListings: Listing[] = [
  {
    id: "1",
    title: "Modern Downtown Loft",
    description: "Stunning open-concept loft in the heart of downtown with floor-to-ceiling windows, exposed brick walls, and premium finishes throughout. Steps from dining, nightlife, and public transit.",
    price: 2800,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    city: "Austin",
    state: "TX",
    address: "456 Congress Ave",
    listingType: "rent",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop",
    ],
    amenities: ["In-Unit Laundry", "Rooftop Deck", "Gym", "Concierge", "Parking"],
    createdAt: "2025-12-01",
    sellerId: "s1",
  },
  {
    id: "2",
    title: "Charming Craftsman Bungalow",
    description: "Beautifully restored 1920s Craftsman with original hardwood floors, updated kitchen with quartz counters, and a large backyard perfect for entertaining. Quiet, tree-lined street.",
    price: 425000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    city: "Portland",
    state: "OR",
    address: "2312 SE Hawthorne Blvd",
    listingType: "sale",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop",
    ],
    amenities: ["Hardwood Floors", "Backyard", "Garage", "Updated Kitchen", "Fireplace"],
    createdAt: "2025-11-15",
    sellerId: "s2",
  },
  {
    id: "3",
    title: "Luxury Waterfront Condo",
    description: "Breathtaking waterfront views from this 15th-floor corner unit. Two master suites, chef's kitchen, spa-like bathrooms, and a wraparound terrace perfect for sunsets.",
    price: 5200,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2200,
    city: "Miami",
    state: "FL",
    address: "1000 Brickell Ave",
    listingType: "rent",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    ],
    amenities: ["Waterfront", "Pool", "Spa", "Valet Parking", "Smart Home", "Gym"],
    createdAt: "2025-12-10",
    sellerId: "s1",
  },
  {
    id: "4",
    title: "Cozy Studio Near Campus",
    description: "Efficient and bright studio apartment near the university. Ideal for students or young professionals. All utilities included. On-site laundry and bike storage.",
    price: 1100,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    city: "Denver",
    state: "CO",
    address: "800 E Colfax Ave",
    listingType: "rent",
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
    ],
    amenities: ["Utilities Included", "Bike Storage", "Laundry", "Near Transit"],
    createdAt: "2025-12-05",
    sellerId: "s3",
  },
  {
    id: "5",
    title: "Elegant Victorian Townhouse",
    description: "Stunning 4-bedroom Victorian townhouse with original details preserved, modern updates, gourmet kitchen, private garden, and two-car garage. Walkable neighborhood.",
    price: 875000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3200,
    city: "San Francisco",
    state: "CA",
    address: "1420 Haight St",
    listingType: "sale",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    ],
    amenities: ["Garden", "Garage", "Fireplace", "Bay Windows", "Crown Molding", "Deck"],
    createdAt: "2025-11-20",
    sellerId: "s2",
  },
  {
    id: "6",
    title: "Modern Suburban Family Home",
    description: "Brand new construction with open floor plan, smart home technology, energy-efficient appliances, and a generous yard in a top-rated school district.",
    price: 550000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2800,
    city: "Charlotte",
    state: "NC",
    address: "5500 Providence Rd",
    listingType: "sale",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    ],
    amenities: ["Smart Home", "Solar Panels", "2-Car Garage", "Backyard", "Walk-In Closets"],
    createdAt: "2025-12-12",
    sellerId: "s3",
  },
];

export const mockApplications: Application[] = [
  {
    id: "a1",
    listingId: "1",
    applicantName: "Sarah Chen",
    applicantEmail: "sarah@example.com",
    matchScore: 92,
    creditScore: 780,
    income: 95000,
    evictions: 0,
    bankruptcy: false,
    status: "pending",
    createdAt: "2025-12-15",
  },
  {
    id: "a2",
    listingId: "1",
    applicantName: "James Wilson",
    applicantEmail: "james@example.com",
    matchScore: 74,
    creditScore: 680,
    income: 72000,
    evictions: 0,
    bankruptcy: false,
    status: "pending",
    createdAt: "2025-12-16",
  },
  {
    id: "a3",
    listingId: "1",
    applicantName: "Maria Rodriguez",
    applicantEmail: "maria@example.com",
    matchScore: 45,
    creditScore: 560,
    income: 48000,
    evictions: 1,
    bankruptcy: true,
    status: "rejected",
    createdAt: "2025-12-14",
  },
];
